export function createConfigHistory({$,run,review,getDocument,getKind,setDraft}){
  $('#config-view').insertAdjacentHTML('beforeend','<section class="panel module-panel"><div class="panel-heading"><h3>Configuration history</h3><button type="button" id="config-history-refresh" class="secondary-button">Refresh history</button></div><p class="settings-help">Backups are grouped by application. Review the current source path before restoring an older configuration.</p><div class="button-row"><select id="config-history-select" aria-label="Saved configuration backup"></select><button type="button" id="config-history-compare" class="secondary-button">Compare</button><button type="button" id="config-history-restore" class="primary-button" disabled>Review restore to draft</button></div><p id="config-history-status" role="status"></p><div class="module-columns"><section><h4>Current draft</h4><pre id="history-current" class="output compact-output"></pre></section><section><h4>Selected backup</h4><pre id="history-backup" class="output compact-output"></pre></section></div></section>');
  let generation=0,backup=null;
  const reset=()=>{backup=null;$('#config-history-restore').disabled=true;$('#history-current').textContent='';$('#history-backup').textContent='';};
  async function refresh(){const current=++generation;reset();$('#config-history-select').replaceChildren();$('#config-history-status').textContent='Loading saved versions…';
    try{const rows=await run('configuration_history',{kind:getKind()});if(current!==generation)return;for(const row of rows){const option=document.createElement('option');option.value=row.name;const stamp=Number(row.name.match(/-(\d+)\.bak$/)?.[1]);option.textContent=`${Number.isFinite(stamp)?new Date(stamp).toLocaleString():row.name} · ${row.bytes} bytes`;$('#config-history-select').append(option);}$('#config-history-status').textContent=rows.length?`${rows.length} saved versions (latest 100).`:'No previous versions saved yet.';}catch(error){if(current===generation)$('#config-history-status').textContent=`History unavailable: ${error.message||error}`;}}
  async function compare(){const current=++generation;reset();const name=$('#config-history-select').value,kind=getKind();if(!name)return;$('#config-history-status').textContent='Loading backup…';
    try{const content=await run('configuration_backup',{kind,name});if(current!==generation)return;backup={kind,name,content};$('#history-current').textContent=$('#config-text').value;$('#history-backup').textContent=content;$('#config-history-status').textContent=`Comparing ${name} with your current draft.`;$('#config-history-restore').disabled=!getDocument();}catch(error){if(current===generation)$('#config-history-status').textContent=`Could not load backup: ${error.message||error}`;}}
  $('#config-history-refresh').addEventListener('click',refresh);$('#config-history-compare').addEventListener('click',compare);$('#config-history-select').addEventListener('change',()=>{generation++;reset();});
  $('#config-history-restore').addEventListener('click',async()=>{const chosen=backup,doc=getDocument(),current=generation;if(!chosen||!doc||chosen.kind!==getKind())return;
    const accepted=await review('Restore saved configuration to draft?',`Source: ${doc.path}\nBackup: ${chosen.name}\nThis replaces the current unsaved draft. Use Review & save afterward to validate and write it.`,`CURRENT DRAFT\n${$('#config-text').value}\n\nBACKUP\n${chosen.content}`,'Load backup into draft');
    if(accepted&&current===generation&&getDocument()===doc){setDraft(chosen.content);$('#config-history-status').textContent='Backup loaded as an unsaved draft. Review & save validates it and backs up the current file.';}
  });
  return {refresh,invalidate(){generation++;reset();$('#config-history-select').replaceChildren();}};
}
