export function catalogInstructions(data) {
  if(!/^[a-f0-9]{40}$/i.test(data?.latest||'')||!/^[a-f0-9]{40}$/i.test(data?.bundled||''))throw new Error('Catalog check returned an invalid revision');
  return data.latest===data.bundled?'Bundled catalog matches the current default branch.':`After reviewing the comparison and committing your existing app changes, run in your Command Center source checkout:\nnpm run toolbox:pin -- ${data.latest}\nnpm run desktop:install\n\nRestart the installed app after the build. Your running catalog stays unchanged until then.`;
}
export function createToolboxUpdates({$,state,run,action,escapeHtml:e}) {
  $('#toolbox-view .toolbox-intro').insertAdjacentHTML('afterend',`<details class="panel module-panel" id="toolbox-updates"><summary>Toolbox Updates</summary><p>Update checks cover package sources across your system. Toolbox entries do not yet track which packages you installed.</p><div class="button-row"><button type="button" class="secondary-button" id="catalog-update-check">Check catalog updates</button><button type="button" class="secondary-button" id="catalog-update-compare" disabled>Compare revisions</button></div><p id="catalog-update-status" role="status">Catalog updates require rebuilding Command Center.</p><pre id="catalog-update-command" class="output compact-output"></pre><div class="button-row"><button type="button" class="secondary-button" id="installed-update-check">Check installed-tool updates</button><label>Run updates in<select id="updates-terminal"><option value="embedded">Embedded terminal</option><option value="external">External terminal</option></select></label></div><p id="installed-update-status" role="status">Checks may contact Flatpak remotes. Detecting full-upgrade loads your fish configuration; it does not invoke the function.</p><div id="installed-update-groups" class="module-columns"></div><h3>Review & update</h3><div id="installed-update-actions" class="button-row"></div><p id="installed-update-manual">Check first to detect supported update workflows.</p><p>Use one broad workflow or individual package managers. Full-upgrade and Topgrade may already include Flatpak. Terminal output can be reviewed/exported through the existing terminal controls; Activity records the job result.</p></details>`);
  let revision=null;
  for(const id of ['catalog-update-check','installed-update-check'])$('#'+id).disabled=!state.desktop;
  $('#catalog-update-check').addEventListener('click',async()=>{
    const b=$('#catalog-update-check');b.disabled=true;revision=null;$('#catalog-update-compare').disabled=true;$('#catalog-update-command').textContent='';$('#catalog-update-status').textContent='Checking Toolbox default branch…';
    try{const data=await run('toolbox_catalog_update');const instructions=catalogInstructions(data);revision=data.latest;$('#catalog-update-status').textContent=`Bundled ${data.bundled.slice(0,7)} · Default branch ${data.latest.slice(0,7)}${data.latest!==data.bundled?' · Different revision available (review before adopting)':''}`;$('#catalog-update-command').textContent=instructions;$('#catalog-update-compare').disabled=data.latest===data.bundled;}
    catch(error){$('#catalog-update-status').textContent=`Check failed: ${error.message||error}`;}finally{b.disabled=false;}
  });
  $('#catalog-update-compare').addEventListener('click',async()=>{if(!revision)return;try{await run('toolbox_compare',{revision});}catch(error){$('#catalog-update-status').textContent=String(error);}});
  $('#installed-update-check').addEventListener('click',async()=>{
    const b=$('#installed-update-check');b.disabled=true;$('#installed-update-actions').replaceChildren();$('#installed-update-groups').replaceChildren();$('#installed-update-status').textContent='Checking package sources and detecting workflows…';$('#installed-update-manual').textContent='';
    try{const data=await run('toolbox_update_checks');
      $('#installed-update-groups').innerHTML=data.groups.map(g=>`<section class="panel module-panel"><h4>${e(g.name)}</h4><p>${e(g.note)}</p><strong>${e(g.check.state==='none-reported'?'No entries reported by this query':g.check.state)}</strong><p>${e(g.check.detail||'')}</p><pre class="output compact-output">${e(g.check.output||'')}</pre></section>`).join('');
      const w=data.workflows;const choices=[['full-upgrade','Run full-upgrade',w.fullUpgrade],['topgrade','Run Topgrade',w.topgrade],['garuda','Update Garuda',w.garuda],['arch','Update Arch packages',w.arch&&!w.garuda],['flatpak-user','Update user Flatpaks',w.flatpak],['flatpak-system','Update system Flatpaks',w.flatpak]];
      $('#installed-update-actions').innerHTML=choices.filter(c=>c[2]).map(([id,label])=>`<button type="button" class="secondary-button" data-update-workflow="${id}">${label}</button>`).join('')||'<p>No built-in updater detected. Configure a custom action for your system.</p>';
      $('#installed-update-actions').querySelectorAll('button').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{const id=await action({action:'tool-update',toolId:button.dataset.updateWorkflow,terminalMode:$('#updates-terminal').value});if(id)$('#installed-update-status').textContent='Update started. Results shown above are now stale; check again after completion.';}catch(error){$('#installed-update-status').textContent=`Update not started: ${error.message||error}`;}finally{button.disabled=false;}}));
      $('#installed-update-manual').textContent=data.manual;$('#installed-update-status').textContent=`Checked ${new Date(data.checkedAt).toLocaleString()}. Cached results are not a guarantee of the latest versions.`;
    }catch(error){$('#installed-update-status').textContent=`Check failed: ${error.message||error}`;}finally{b.disabled=false;}
  });
}
